require("./test_cases/AB Testing");
require("./test_cases/Remove Elements");
require("./test_cases/Basic Auth");
require("./test_cases/Broken Image");
require("./test_cases/Challenging DOM");
require("./test_cases/Checkboxes");
require("./test_cases/Context Menu");
require("./test_cases/Digest Authentication");
require("./test_cases/Disappearing Elements");
require("./test_cases/Drag and Drop");/*
require("./test_cases/Dropdown List");
require("./test_cases/Dynamic Content");
require("./test_cases/Dynamic Loading");
require("./test_cases/Entry Ad");
require("./test_cases/Exit Intent");
require("./test_cases/File Downloader");
require("./test_cases/File Uploader");
require("./test_cases/Floating Menu");
require("./test_cases/Forgot Password");
require("./test_cases/Login Page");
require("./test_cases/Frames");
require("./test_cases/Geolocation");
require("./test_cases/Horizontal Slider");
require("./test_cases/Hovers");
require("./test_cases/Infinite Scroll");
require("./test_cases/Inputs");
require("./test_cases/JQueryUI - Menu");
require("./test_cases/JavaScript Alerts");
require("./test_cases/Key Press");
require("./test_cases/Large & Deep DOM");
require("./test_cases/Opening a new window");
require("./test_cases/Notification Message");
require("./test_cases/Redirection");
require("./test_cases/Secure File Download");
require("./test_cases/Shadowdom");
require("./test_cases/Shifting Content");
require("./test_cases/Sortable Data Tables");
require("./test_cases/Typos");
require("./test_cases/Dynamic Controls");*/