// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.security.sandbox.content.win32k-experiment.enrollmentStatus", 2);
user_pref("app.normandy.user_id", "8573ca20-c2c6-4335-9e75-f2b428ab53fb");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 3);
user_pref("app.update.background.previous.reasons", "[\"app.update.langpack.enabled=true and at least one langpack is installed\"]");
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1655633036);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1655633012);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1655633008);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e4c1810c-758e-4886-bc38-9469c5adf6ab}");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1655633005);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 127);
user_pref("browser.newtabpage.activity-stream.impressionId", "{515e271e-f075-40d3-86bb-dd7e2e4e97a3}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1655633007);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1655633015839");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1655654615839");
user_pref("browser.search.region", "HR");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220608170832");
user_pref("browser.startup.homepage_override.mstone", "101.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1655633008);
user_pref("browser.theme.content-theme", 1);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1655633010740");
user_pref("distribution.iniFile.exists.appversion", "101.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "HR");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "cdee7a379abd468d8381a390b69fabb0");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220608170832");
user_pref("extensions.lastAppVersion", "101.0.1");
user_pref("extensions.lastPlatformVersion", "101.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"285616f4-aebe-4915-98f7-97883cc9f689\",\"formautofill@mozilla.org\":\"4779ddf6-30c1-4796-ad94-bf7c7d87b659\",\"pictureinpicture@mozilla.org\":\"e709d105-474a-4748-89de-70d9447cda7e\",\"screenshots@mozilla.org\":\"6b269aa1-6a31-4bbf-b942-542bf2431912\",\"webcompat-reporter@mozilla.org\":\"d05049f0-6ab2-4a0b-b081-dd4504548645\",\"webcompat@mozilla.org\":\"a952671c-274c-4cba-beb0-f971200828e3\",\"default-theme@mozilla.org\":\"1645ab71-1ca2-4342-a586-149f11cc3e9d\",\"addons-search-detection@mozilla.com\":\"86dc4c5e-ce29-41e0-ac98-8cd311592a1f\",\"google@search.mozilla.org\":\"144d93d3-4ba6-4f6e-8960-9d709ba2e097\",\"amazondotcom@search.mozilla.org\":\"cf273042-a7be-4d63-9241-91785873335e\",\"wikipedia@search.mozilla.org\":\"b65af376-ad3a-4418-bf14-90263cd20878\",\"eudict@search.mozilla.org\":\"afb6f338-a460-4cbc-9a56-58e2ee84fba0\",\"bing@search.mozilla.org\":\"83670042-8d1c-4acb-b6ce-ce5c62faeaae\",\"ddg@search.mozilla.org\":\"4c61a3d0-5d82-4aac-9ccd-38dbddfb76a2\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1655633010);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20220608170832");
user_pref("gfx-shader-check.device-id", "0x0416");
user_pref("gfx-shader-check.driver-version", "20.19.15.5126");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x0416");
user_pref("sanity-test.driver-version", "20.19.15.5126");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20220608170832");
user_pref("security.sandbox.content.tempDirSuffix", "{9c1e57c0-a382-4021-bbe7-e5e4514dbdd1}");
user_pref("security.sandbox.content.win32k-experiment.startupEnrollmentStatus", 2);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1655633005);
user_pref("toolkit.telemetry.cachedClientID", "efe7d85f-5ebc-417b-9ff2-c36ad523abb8");
user_pref("toolkit.telemetry.previousBuildID", "20220608170832");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
